require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'BtzBankMobile' do
  use_unimodules!
  config = use_native_modules!
  
  use_react_native!(:path => config["reactNativePath"])

  /adding camera permission/
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  /end/

  if !ENV['CI']
    use_flipper!({ 'Flipper' => '0.80.0' })
    post_install do |installer|
      flipper_post_install(installer)
    end
  end
end
